name: Ping Supabase to Prevent Pause

on:
  schedule:
    - cron: '0 9 * * 1,4'
  workflow_dispatch:

permissions:
  contents: write  # Allows the action to "poke" the repo to keep it active
  actions: write   # Necessary for the keepalive action

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ping Supabase
        run: curl -f https://${{ secrets.VERCEL_URL }}/api/ping

      - name: Keepalive Workflow
        uses: gautamkrishnar/keepalive-workflow@v2
        with:
          use_api: true
