name: Ping Supabase to Prevent Pause

on:
  schedule:
    - cron: '0 9 * * 1,4'  # Runs at 9 AM UTC every Monday and Thursday
  workflow_dispatch:  # Allows manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase
        run: curl -f https://${{ secrets.VERCEL_URL }}/api/ping
